version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node_appjs

  node_appjs:
    container_name: re_server
    build: .
    image: test8:v1
    # ports:
    #   - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - 4000
    environment:
      - NODE_ENV=dev 
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=abc
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - sql-db:/var/lib/mysql

volumes:
   sql-db: